### ISSUE TITLE
Error in Home Assistant (result["altitude"] = result.pop("alt"))

### ISSUE THREAD

**Issue by skleijkers** [corvy/ha-addons#3]
Hi,

I'm getting the following error in the addon (logfile) when starting:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting GPSD with device "/dev/ttyACM0"...
Traceback (most recent call last):
  File "/gpsd2mqtt.py", line 103, in <module>
Connected to MQTT broker
    result["altitude"] = result.pop("alt")
                         ^^^^^^^^^^^^^^^^^
KeyError: 'alt'
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

Is there a way to debug further?

Stefan

**Comment by corvy** [comment]
Seems your GPS does not report altitude. I think I can fix that. Could you turn on debug and see if we get a full NMEA JSON output?

**Comment by skleijkers** [comment]
Hi,

Enabled debug, didn't a lot of more information:
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
Starting GPSD with device "/dev/ttyACM0"...
These are the options in use.
Serial device: /dev/ttyACM0
Traceback (most recent call last):
  File "/gpsd2mqtt.py", line 103, in <module>
Device Baudrate: 9600
MQTT Hostname: core-mosquitto
MQTT TCP Port: 1883
MQTT Username: gpsuser
MQTT Password: XXXXXXXX
Debug enabled: True
Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=b''
Sending PUBLISH (d0, q0, r0, m1), 'b'homeassistant/device_tracker/gpsd/config'', ... (164 bytes)
Received CONNACK (0, 0)
Connected to MQTT broker
    result["altitude"] = result.pop("alt")
                         ^^^^^^^^^^^^^^^^^
KeyError: 'alt'
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

Stefan

**Comment by skleijkers** [comment]
Hi,

I just got an update from HA itself and it seems now it is working... bit weird but debug output of the addon:
Published: {'class': 'TPV', 'device': '/dev/ttyACM0', 'status': 2, 'mode': 3, 'time': '2023-06-07T21:10:24.000Z', 'ept': 0.005, 'altHAE': 98.9, 'altMSL': 52.5, 'epx': 1.803, 'epy': 1.893, 'epv': 5.75, 'magvar': 1.8, 'speed': 0.062, 'climb': 0.2, 'eps': 3.78, 'epc': 11.5, 'geoidSep': 46.4, 'eph': 3.325, 'sep': 5.795, 'altitude': 52.5, 'longitude': X.7244955, 'latitude': X.848089833} to topic: gpsd/attribute
Sending PUBLISH (d0, q0, r0, m492), 'b'gpsd/state'', ... (6 bytes)
Sending PUBLISH (d0, q0, r0, m493), 'b'gpsd/attribute'', ... (374 bytes)

Stefan

**Comment by corvy** [comment]
The problem was that the first message from the GPS did not send the altitude and since I rename this attribute in the device_tracker the script fails. In v.0.0.108 this is not checked. So if the GPS does not send alt (or lat or lon) the script just continues and does not rewrite. So now it should not fail anymore, even if it does not sent alt etc. 

The debug message is basically the JSON coming from the GPS device. That looks just fine :) 

I will make some more readme, but one hint of what I did was to create a person (for my boat, that is my use-case) and then added the device tracker "device_tracker.gps_location" to track the location of that person. Then I added a photo for that "person" (boat!) and then added a map. That makes it look a bit cool :) 

![image](https://github.com/corvy/ha-addons/assets/138292/6834caab-d35d-4466-9bb2-bc32cca806d4)

But sidetrack aside! Upgrade to 0.0.108 to make sure the add-on does not crash when starting.
